FROM php:7.4-fpm

# install the modules we need
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions gd xdebug ds pdo_mysql redis

# Use the default development configuration
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# copy pool config
COPY www.conf /usr/local/etc/php-fpm.d

# set xdebug config
COPY xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# copy bash config
COPY .bashrc /root

# set up default site
RUN mkdir -p /usr/local/apache2/htdocs
RUN echo "<?php phpinfo();" >> /usr/local/apache2/htdocs/index.php