version: "3.9"

services:
    dns:
        container_name: "dns"
        build:
            context: conf/dns
        cap_add:
            - NET_ADMIN
        networks:
            devnet:
                ipv4_address: 172.20.0.11

    db:
        container_name: "mysql"
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_ROOT_HOST=%
            - MYSQL_USER=homestead
            - MYSQL_PASSWORD=secret
        # healthcheck:
        #     test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASS
        volumes:
            - mysql-data:/var/lib/mysql
            - ./conf/mysql:/etc/mysql
        networks:
            - devnet
    
    redis:
        container_name: "redis"
        image: redis
        ports:
            - 6379:6379
        networks:
            - devnet

    php:
        container_name: "php"
        build: 
            context: conf/php
        volumes:
            - /Volumes/Code/craft-server:/var/www/craft
            - /Volumes/Code/content-api:/var/www/api
            - /Volumes/Code/re-flow-admin:/var/www/admin
            - /var/www/craft/core/develop/current/src
        networks:
            - devnet
        dns: 172.20.0.11

    apache:
        container_name: "apache"
        build: 
            context: conf/apache2
        depends_on:
            - php
            - db
            - redis
        ports:
            - 80:80
            - 443:443
        volumes:
            - /Volumes/Code/craft-server:/var/www/craft
            - /Volumes/Code/content-api:/var/www/api
            - /Volumes/Code/re-flow-admin:/var/www/admin
            - /var/www/craft/core/develop/current/src
        networks:
            devnet:
                ipv4_address: 172.20.0.10

volumes:
    mysql-data:

networks:
  devnet:
    ipam:
      config:
        - subnet: 172.20.0.0/16